# Generated by Django 4.1.1 on 2022-09-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bookpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="type",
            field=models.CharField(
                choices=[("A", "A module"), ("B", "B module"), ("O", "Other")],
                default="O",
                max_length=5,
            ),
        ),
    ]
