# Generated by Django 4.1.1 on 2022-09-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_book_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookpoint",
            unique_together={("book", "page", "h")},
        ),
    ]
